// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/Cards.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Header.vue')['default']
    Room: typeof import('./src/components/Room.vue')['default']
    RoomSelection: typeof import('./src/components/RoomSelection.vue')['default']
    Round: typeof import('./src/components/Round.vue')['default']
    VotingCard: typeof import('./src/components/VotingCard.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
